TIMEOUT_ROLE_ID: "354313345979121664"
# Role to use for spam-prevention role.

TIMEOUT_CHANNEL_ID: "354312520447688704"
# Channel to use for redirection of spammers.

HEAVY_TIMEOUT_ROLE_ID: "354329328688955392"
# If the role fails, secondary role will mute spammers.

TIMEOUT_BYPASS_ROLE_ID: "000000000000000000"

SERVER_ID: "331900978548965376"
# Server ID for the bot.
